### ISSUE TITLE
Balken ist zu Groß. Beißt sich mit DUI.

### ISSUE THREAD

**Issue by Salbei2500** [gruppe-adler/TvT_HuntingHoppers.fallujah#8]
Balken ist zu Groß. Beißt sich mit DUI.

![20200817205851_1](https://user-images.githubusercontent.com/12427159/90436921-c66c6280-e0d1-11ea-9d53-e181f19cb47f.jpg)

**Comment by nomisum** [comment]
dein dui is zu groß ^^ #4k

**Comment by Salbei2500** [comment]
Ich glaube die hälft vom Bildschirm sollte dir reichen

**Comment by diwako** [comment]
https://github.com/gruppe-adler/TvT_HuntingHoppers.fallujah/blob/a40f40486af8c09e618e9d8e5fc9fd46247d7a9e/USER/functions/fn_areaBarCreate.sqf#L3-L8

In general i would say, use `pixelGrid` for x any y position values.

If you want the progress bar go beneath DUI then you need to create the control before DUI creates its controls. DUI creates it on PostInit for this reason, so it is possible to define yours in PreInit or init scripts by the mission.

Example from the CBRN script
```sqf
// display gas mask overlay above ace nvg and below DUI
if !(isNil "ace_nightvision") then {
    "ace_nightvision_display" cutFadeOut 0;
};
"cbrn_gasmask_overlay" cutFadeOut 0;
if !(isNil "diwako_dui_radar") then {
    "diwako_dui_compass" cutFadeOut 0;
    "diwako_dui_namebox" cutFadeOut 0;
};
```
